### ISSUE TITLE
Syntax Error when running the server

### ISSUE THREAD

**Issue by zhinuoli** [PhDN/NoCheat#8]
#### Issue description
Syntax Error when running the server

#### Steps to reproduce the issue

1. Followed steps 1-3 in developer guidelines to set up the environment.
2. Reached error on step 4

#### What's the expected result?

- Successfully run the server.

#### What's the actual result?

- Syntax Error

#### Additional details / screenshot

- Used Mac terminal
- ![image](https://user-images.githubusercontent.com/64811271/222023457-ce17a196-d689-4488-8656-4bf8b41c468f.png)

**Comment by SNSTRUTHERS** [comment]
This occurs when attempting to run the application using Python 2.7. From the looks of it the Conda environment wasn't set up correctly for some reason.
